
[metadata.heroku]
  root-package = "github.com/arnoldusantonius/micromdm/cmd/bla"
  go-version = "go1.9.3"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "v1.3.0"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "v0.6.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "v1.3.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "v0.8.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "v1.1.0"

[[constraint]]
  name = "github.com/micromdm/mdm"
  branch = "master"
